def project = 'synetic-k8s-poc'
def appName = 'php-poc'
def feSvcName = "${appName}"
def imageTag = "gcr.io/${project}/${appName}:${env.BUILD_NUMBER}"

pipeline {
  agent {
    kubernetes {
      label "${appName}-jenkins"
      defaultContainer 'jnlp'
      yaml """
apiVerson: v1
kind: Pod
metadata:
labels:
  component: agents
spec:
  # Use service account that can deploy to all namespaces
  containers:   
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
  - name: gcloud
    image: google/cloud-sdk
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
"""
}
  }
  stages {

    stage('Build image') {
      steps {
        container('gcloud') {
          sh "docker build -t ${imageTag} ."
        }
      }
    }

    stage('Upload image to registry') {
      steps {
        container('gcloud') {
          sh "gcloud docker --authorize-only"
          sh "docker \push  ${imageTag}"
        }
      }
    }

    stage('Test') {
      steps {
        container('gcloud') {
          echo "testing ${imageTag}"
        }
      }
    }

  }
}