def project = 'synetic-k8s-poc'
def appName = 'php-poc'
def feSvcName = "${appName}"
def imageTag = "gcr.io/${project}/${appName}:${env.BUILD_NUMBER}"

pipeline {
  agent {
    kubernetes {
      label "${appName}-jenkins"
      defaultContainer 'jnlp'
    }
  }
  stages {

    stage('Build image') {
      steps {
        container('gcloud') {
          sh "docker build -t ${imageTag} ."
        }
      }
    }

    stage('Upload image to registry') {
      steps {
        container('gcloud') {
          sh "gcloud docker -- push ${imageTag}"
        }
      }
    }

    stage('Test') {
      steps {
        container('jlnp') {
          echo "testing ${imageTag}"
        }
      }
    }

  }
}