def project = 'synetic-k8s-poc'
def appName = 'php-poc'
def feSvcName = "${appName}"
def imageTag = "gcr.io/${project}/${appName}:${env.BUILD_NUMBER}"

pipeline {
  agent {
    kubernetes {
      label "${appName}-jenkins"
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: jenkins-1
  containers:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    command:
    - cat
    tty: true
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
"""
}
  }
  stages {

    stage('Build image') {
      steps {
        container('jnlp') {
          sh "docker build -t ${imageTag} ."
        }
      }
    }

    stage('Upload image to registry') {
      steps {
        container('gcloud') {
          sh "gcloud docker -- push ${imageTag}"
        }
      }
    }

    stage('Test') {
      steps {
        container('jlnp') {
          echo "testing ${imageTag}"
        }
      }
    }

  }
}