# Service
apiVersion: v1
kind: Service

metadata:
  name: php-poc-service
  labels:
    app: php-poc  

spec:
  type: NodePort

  selector:
    app: php-poc

  ports:
    - port: 80

---
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: php-poc-ingress
  labels:
    app: php-poc  

spec:
  backend:
    serviceName: php-poc-service
    servicePort: 80
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: php-poc-deployment
  labels:
    app: php-poc

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-poc
    spec:
      containers:
      - image: eu.gcr.io/synetic-k8s-poc/php-poc:46
        name: php-poc
        ports:
        - containerPort: 80
